### ISSUE TITLE
[NG] : ng-blur non dovrebbe essere usato per lanciare i setter delle variabili

### ISSUE THREAD

**Issue by michelesr** [befair/gasistafelice#100]
`ng-blur` viene lanciato solo quando viene perso il focus dell'elemento del dom. Utilizzare un getter/setter risulta piu' appropriato.

Fare riferimento a:

Binding to a getter/setter section of [ngModel doc](https://docs.angularjs.org/api/ng/directive/ngModel)

Nota: questo va marcato come enhancement

**Comment by michelesr** [comment]
grep "ng-blur" -H -r .
    ./ui/components/basket/basket.html:  <input type="text" class="form-control"    ng-blur="basket.pm.change(item);" ng-model="item.quantity" name="form-{{$index}}-ordered_amount" id="form-{{$index}}-ordered_amount"/>
    ./ui/components/order/order.html: <input type="text" class="form-control form-control-ordered_amount" ng-blur="order.pm.change(product)" ng-model="product.quantity"  id="form-{{$index}}-ordered_amount" ng-pattern="/^(\d)+(\.\d+)*$/" required/>

**Comment by feroda** [comment]
la funzione ProductManager.change serve a valutare ed eventualmente segnalare se il valore inserito è minore della quantità minima inseribile o se multipla dell'incremento previsto per un determinato prodotto.

Questa cosa credo si debba fare con ng-blur altrimenti ng-chamge la ripeterebbe ad ogni cambio di valore nlla cella della quantità di prodotto.

Chiuderei questa issue
