### ISSUE TITLE
Bottone per andare nella parte "gestione" (= legacy)

### ISSUE THREAD

**Issue by feroda** [befair/gasistafelice#103]
È necessario esporre un bottone che porti all'interfaccia legacy.

Tutti possono andarci... alla fine anche i gasisti semplici possono vedere altre informazioni del DES andando li.

**Comment by kobe25** [comment]
Non dovremmo limitare l'accesso all'interfaccia legacy allo stretto indispensabile per evitare confusione tra i gasisti?

**Comment by feroda** [comment]
L'interfaccia legacy contiene la visibilità del DES, quindi non la limiterei, al limite mettiamo un bottone "Avanzate".

Inoltre per visualizzare il bottone ai soli profili "gestori" -> dovremmo fare un check sui livelli di accesso, cosa che ora con la ng-gf non facciamo, per questo nella versione dj17-alpha (milestone riferita al ticket) secondo me è importante aggiungere il bottone per tutti.

...pian piano la legacy verrà soppiantata, ma non da qui ad un anno direi

**Comment by kobe25** [comment]
:+1:
