### ISSUE TITLE
[ng] Visualizzare solo il primo GAS di appartenenza di un gasista

### ISSUE THREAD

**Issue by feroda** [befair/gasistafelice#105]
Non credo che funzioni:
disabilitiamo l'appartenenza a più di un GAS per il rilascio di inizio settembre.

Se vogliamo fare una prova...

**Comment by feroda** [comment]
GF prevede l'appartenenza di una gasmember in più GAS, ma per questa milestone togliamo il dropdown menu della selezione del GAS in alto a sinistra e prendiamo solo il primo GAS di appartenenza ritornato dal JSON

**Comment by michelesr** [comment]
Non sembra che ci sia bisogno di modificare il controller, dato che viene caricato solo il primo gas:

        this.load_person = function() {
            $http.get('/api/v1/person/my/?format=json')
            .success( function(data) {
                data.gas_list[0].ui_status = 'active';
                $rootScope.person = data;
                $rootScope.gas_active = data.gas_list[0];
                $rootScope.gm_id = data.gasmembers[0];
                THAT.dataLoaded = true;
            })

Disattivo il menu'.

**Comment by feroda** [comment]
@michelesr Viene settato come attivo il primo gas infatti 👍 confermo.
