### ISSUE TITLE
Sottomodulo django-pro-history

### ISSUE THREAD

**Issue by kobe25** [befair/gasistafelice#106]
@matteo88 il sottomodulo attualmente presente in `submodules/django-pro-history` non e' stato sostituito?

**Comment by matteo88** [comment]
Il sottomodulo non dovrebbe essere sostituito, ma rimosso: non viene più installato e non viene utilizzato dalle altre app, in favore del modulo `django-reversion`

**Comment by kobe25** [comment]
Si', il senso era proprio quello.  Andrebbe fatto un `rm -rf submodules/django-pro-history && git commit -a`, giusto?

**Comment by matteo88** [comment]
Il modo corretto di rimuovere un sottomodulo è, partendo dalla root di GF:

$ `git submodule deinit submodules/django-pro-history`

$ `rm -rf .git/modules/submodules/django-pro-history`

Rimuovere le righe corrispondente al sottomodulo in .gitmodules`

$ `git rm --cached submodules/django-pro-history`

$ `rm -rf submodules/django-pro-history`

$ `git commit -a`
