### ISSUE TITLE
400 Bad Request per l'ambiente di CI/produzione

### ISSUE THREAD

**Issue by kobe25** [befair/gasistafelice#107]
L'errore si verifica sostituendo il default `APP_ENV=dev` con `APP_ENV=prod` in `settings.env` e visitando:

* http://localhost:8080/gasistafelice/ (tramite NGiNX)
* http://localhost:7000/gasistafelice/ (direttamente verso uWSGI)

Aggiungo che la variabile d'ambiente influenza principalmente dei parametri in `gasistafelice/gf/settings.py`

**Comment by feroda** [comment]
che cazzo di niubbi che siete ;) 

https://docs.djangoproject.com/en/1.8/topics/settings/ le prime 10 righe. Se DEBUG=False => ALLOWED_HOSTS deve essere settato. Per renderlo accessibile a tutti si mette ['*'], in realtà non so se dietro proxy nginx potremo mettere ['localhost'] penso di no, ma ve lo lascio provare ;)

A voi l'onore della patch

**Comment by feroda** [comment]
mi sentivo in effetti triste per il commento e volevo dare meno visibilità a questa issue ;)
