### ISSUE TITLE
Requisito mancante: server SMTP

### ISSUE THREAD

**Issue by kobe25** [befair/gasistafelice#108]
Manca un server SMTP (Postfix) per gli ambienti `stage` e `prod`

**Comment by feroda** [comment]
imho questo non dovrebbe essere un requisito. Di solito nelle applicazioni ci sono le opzioni di configurazione del server SMTP, così come le mette Django. Le dovremmo esporre nel settings.py di default non impostate in modo che ognuno possa abilitare un SMTP in locale o un server esterno se vuole. 

Nella documentazione dovremmo dire "se volete che il sistema mandi le email dovete configurare un server SMTP. Si consiglia di appoggiarsi ad un server esterno..." (e magari mettiamo le impostazioni di Google/Yahoo se si possiede un account li. Mettere un server SMTP già pronto darebbe vari problemi come ad esempio reti friltrate vedi IP pubblici telecom e vedi SPAM. Che ne pensate?

**Comment by kobe25** [comment]
Premetto che la issue (come specificato) non e' relativa ad ambienti `dev` in cui in genere si lavora dietro NAT e dove le mail vengono invece scritte su file, ma a quelli `stage/prod` in cui si presuppone che ci sia bisogno di un server SMTP, integrato nell'applicazione o come servizio esterno.

IMHO piuttosto che come parte integrante dell'applicazione (come Postgres) potrebbe essere piu' opportuno proporlo come servizio esterno di cui andrebbero quindi specificate:

* configurazioni necessarie per connettere il backend al server SMTP
* caratteristiche necessarie del server SMTP stesso

Dove per servizio esterno s'intende sia un server SMTP all'interno della stessa infrastruttura ma comunque svincolato dall'applicazione, oppure un SaaS (Google, etc).

**Comment by feroda** [comment]
Grazie per la specificazione che è in **stage** e **prod**, per il resto differisce in qualcosa rispetto a quello che dicevo io? ;) Mi sembra di no, quindi siamo allineati, quindi è da documentare più che altro giusto?

**Comment by kobe25** [comment]
Provo a riscrivere.

Il "diff"  e' se vale la pena (o meno), oltre ad un SaaS esterno del tutto, di usare anche un Postfix slegato dall'applicazione ma interno all'infrastruttura in cui gira.  In quest'ultimo caso bisogna, oltre che documentare le configurazioni per l'accesso dall'applicazione a Postfix, anche documentare come deve essere configurato questo Postfix (vedi `main.cf`, etc).

**Comment by feroda** [comment]
No. Non insegniamo a configurare un server SMTP

**Comment by kobe25** [comment]
:+1:

**Comment by kobe25** [comment]
Rileggendo meglio, preciso che non dovremmo comunque insegnare a configurare un server SMTP, ma (al massimo) fornirne uno gia' pronto e configurato, come un'immagine Docker `befair/postfix` ;-)

Comunque non e' questo il caso, dunque apro #160 per la documentazione/configurazione.

**Comment by warp10** [comment]
condivido in toto,
anche se per me era scontato.

Bravo che hai chiuso questo e aperto un'altra issue
Luca

On 09/20/2015 11:25 AM, Antonio Esposito wrote:
>
> Rileggendo meglio, preciso che non dovremmo comunque insegnare a 
> configurare un server SMTP, ma (al massimo) fornirne uno gia' pronto e 
> configurato, come un'immagine Docker |befair/postfix| ;-)
>
> Comunque non e' questo il caso, dunque apro #160 
> <https://github.com/befair/gasistafelice/issues/160> per la 
> documentazione/configurazione.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/befair/gasistafelice/issues/108#issuecomment-141762252>.
>

-- 
Luca Ferroni
http://www.befair.it - http://www.lucaferroni.it
Tel: +39 328 9639660
LinkedIn: http://www.linkedin.com/in/lucaferroni
