### ISSUE TITLE
La modalita' di mantenimento non disattiva la chiusura degli ordini

### ISSUE THREAD

**Issue by kobe25** [befair/gasistafelice#112]
Attualmente con `MAINTENANCE_MODE = True` nei settings non viene disattivata l'esecuzione (periodica) dell'`order_fix_state`.

**Comment by feroda** [comment]
l'ho fatto io per toglierci il pensiero...

**Comment by kobe25** [comment]
:+1:

Purtroppo l'errore rimane per `master-dj17` che era il principale branch di riferimento per questa issue.

**Comment by kobe25** [comment]
Per `master-dj17`, potrebbe essere piu' opportuno mettere il controllo in `gasistafelice/gf/wsgi.py` per dare la possibilita' di lanciare il comando a mano da CLI?

**Comment by feroda** [comment]
No compriendo... L'aggiornamento dello stato degli ordini viene lanciato da cron, poi cosa centra con wsgi.py?!?

Il 10 agosto 2015 17:47:02 CEST, Antonio Esposito <notifications@github.com> ha scritto:
>Per `master-dj17`, potrebbe essere piu' opportuno mettere il controllo
>in `gasistafelice/gf/wsgi.py` per dare la possibilita' di lanciare il
>comando a mano da CLI?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/befair/gasistafelice/issues/112#issuecomment-129502007

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by kobe25** [comment]
Prima veniva lanciato da cron, ora viene lanciato direttamente da uWSGI come specificato nel [`wsgi.py`](https://github.com/befair/gasistafelice/blob/master-dj17/gasistafelice/gf/wsgi.py)
