### ISSUE TITLE
[responsive] La navbar collassata non si apre (AngularJS bootstrap)

### ISSUE THREAD

**Issue by feroda** [befair/gasistafelice#115]
Usando AngularJS bisogna adattare l'apertura della navbar collassata come scritto qui
http://stackoverflow.com/questions/14741988/twitter-bootstrap-navbar-with-angular-js-collapse-not-functioning
La risposta rimanda al link: http://jsfiddle.net/z2hLy/

Dubbio da verificare: se implementata in questo modo parte collassata anche su display grandi?

**Comment by michelesr** [comment]
Already fixed with commit bc8683532b8de
