### ISSUE TITLE
Variabili d'ambiente per il CI

### ISSUE THREAD

**Issue by kobe25** [befair/gasistafelice#118]
A causa del #107, son state settate delle variabili d'ambiente poco adatte per il CI.  Infatti queste rispecchiano un ambiente di sviluppo piuttosto che uno di produzione.

Nel `settings_ci.env`, `APP_ENV` dovrebbe essere settato a `prod`

**Comment by kobe25** [comment]
Nel frattempo e' stato risolto il #107

**Comment by michelesr** [comment]
Got it!

**Comment by kobe25** [comment]
Fixato in 2b5da16a
