### ISSUE TITLE
Codice Fiscale del GAS

### ISSUE THREAD

**Issue by matteo88** [befair/gasistafelice#129]
Non è possibile modificare il Codice Fiscale di un GAS da interfaccia, ne creare un GAS con Codice Fiscale.

**Comment by matteo88** [comment]
Proposta di soluzione nella PR # 130.

Verificabile con CURL eseguendo questi comandi:

$ `curl -s -c cookies.txt -b cookies.txt -e "<site_url>/gasistafelice/accounts/login/" "<site_url>/gasistafelice/accounts/login/"`

$ `curl -s -c cookies.txt -b cookies.txt -e "<site_url>/gasistafelice/accounts/login/" -d "csrfmiddlewaretoken=$(grep csrftoken cookies.txt | sed 's/^.*csrftoken\s*//')&username=<username>&password=<password>" -X POST "<site_url>/gasistafelice/accounts/login/"`

$ `curl -s -c cookies.txt -b cookies.txt -e "<site_url>/gasistafelice/accounts/login/" -d "csrfmiddlewaretoken=$(grep csrftoken cookies.txt | sed 's/^.*csrftoken\s*//')&name=&fcc=&id_in_des=&birthday=&headquarter_text=&headquarter=&membership_fee=&contact_set_0_1=&contact_set_0_2=&contact_set_0_0=&contact_set_0_3=&contact_set_1_1=&contact_set_1_2=&contact_set_1_0=&logo=&description=&association_act=&intent_act=" -X POST "<site_url>/gasistafelice/rest/gas/8/gas_details/edit"`

il terzo comando in particolare dovrebbe in caso di successo ritornare l'output:

 `{"error_msg": [], "resource_type": "gas", "resource_id": <id>}`

**Comment by feroda** [comment]
mergiata la PR130 qualche giorno fa
