### ISSUE TITLE
[Test]: Database riservato per il testing

### ISSUE THREAD

**Issue by michelesr** [befair/gasistafelice#141]
La proposta e' quella di predisporre il lancio dei test sul Makefile in questo modo:

1) creazione di un container alternativo per il db con i dati di testing
2) linking del backend con il container del db di test
3) lancio dei test
4) linking del backend con il db di sviluppo

Per quanto riguarda i dati nel database di test si potrebbe agire in questo modo:

1) copiare i dati direttamente nel container con un Dockerfile apposito che includa la COPY dei dati
2) copiare i dati dopo l'avvio del container per il db di testing

La 2 e' piu' rognosa per lo sviluppatore in quanto richiede che il db venga ripulito e riempito di dati ad ogni lancio dei test.

@warp10 @feroda

**Comment by feroda** [comment]
Mi sembra che si possa chiudere ... @michelesr grande!

**Comment by kobe25** [comment]
Why closing without any discussion/comments?

**Comment by feroda** [comment]
Perché @michelesr ha già fatto queste cose per la tesi e messo i comandi nel Makefile. Ma se non l'ha fatto può riaprire la issue che gli è stata assegnata appositamente.

**Comment by michelesr** [comment]
Non c'e' un database specifico per i test, semplicemente viene chiesto con un messaggio in console di usare il comando `make dbtest` prima di `make test`. Per me si puo' chiudere.

>Ma se non l'ha fatto può riaprire la issue che gli è stata assegnata appositamente. 

Non posso riaprire issue, dato che non ho i permessi sul repository.
