### ISSUE TITLE
[Compose]: directory per .yml aggiuntivi e settings.env ?

### ISSUE THREAD

**Issue by michelesr** [befair/gasistafelice#148]
Da considerare lo spostamento di `docker-compose-ci.yml` e `docker-compose-test.yml` in una directory che potrebbe chiamarsi `compose` o `compose-extra` mentre i file solo `ci.yml` e `test.yml`, mentre il `settings.env potrebbe venire spostato da qualche altra parte?

@kobe25 mi affido alle tue capacita' di riordinamento...

**Comment by kobe25** [comment]
Fatta eccezione per il `docker-compose.yml` che manterrei nella root per motivi puramente pratici di utilizzo diretto di Docker Compose via CLI, farei un'unica directory che include:

* gli altri `docker-compose*`
* tutti i `settings*`
* il (futuro) template per OpenShift, `openshift.yaml`?

Al momento non mi viene un nome adatto...  `orchestration`, `deploy` o semplicemente `app`?  da vedere, per ora IMHO va piu' che bene `compose` come hai gia' fatto nel #147
