### ISSUE TITLE
Nella lista degli ordini aperti appaiono anche ordini chiusi

### ISSUE THREAD

**Issue by feroda** [befair/gasistafelice#154]
Si verifica nel frontend gasista, poi non so se è un problema anche di backend

**Comment by feroda** [comment]
Per questa milestone disabilitiamo la visualizzazione di ordini che hanno timestamp di chiusura precedente al timestamp attuale.

Abbiamo notato che è il backend a restituire anche gli ordini chiusi (url: http://localhost:8080/api/v1/gasmember/1/?format=json)

**Comment by michelesr** [comment]
Da quel che ho visto ci son sti filtri:

    GASSupplierOrder.objects.archived()
    GASSupplierOrder.objects.closed()
    GASSupplierOrder.objects.open()

Anche se pero' sembra siano deprecati:

    In [9]: GASSupplierOrder.objects.closed
    Out[9]: <bound method OrderManagerFromOrderQuerySet.closed of <django.utils.deprecation.OrderManagerFromOrderQuerySet object at 0x7f07c1e99210>>

**Comment by michelesr** [comment]
Ho provato a smanettare con il serializzatore passandogli dei queryset, ma non ho avuto risultati rilevanti.

**Comment by feroda** [comment]
> Anche se pero' sembra siano deprecati, dato che stanno su `django.utils.deprecation`

non capisco cosa tu intenda. Vedremo dove sono deprecati (se in Django o in GF e se i managers o i queryset ad esso associati.

> Ho lavorato su `OrderSerializer` che viene richiamato per serializzare il campo `open_orders`.

bravo è proprio quello il punto in cui cercare. La prossima volta per piacere metti il link a [OrderSerializer](https://github.com/befair/gasistafelice/blob/master-dj17/gasistafelice/api_v1/serializers.py#L114).

intanto aggiungo questo commento perché ci stai lavorando, ora non posso fare di più

**Comment by michelesr** [comment]
Ho rimosso i commenti precedenti perche' portano fuori strada. Investigando piu' a fondo ho visto che gli ordini che vengono mostrati di fatto sono aperti (il loro metodo `is_open` ritorna `True`). 

Per quando riguarda i metodi deprecati ecco la loro rappresentazione:


    In [24]: print(GASSupplierOrder.objects.open)
    <bound method OrderManagerFromOrderQuerySet.open of  <django.utils.deprecation.OrderManagerFromOrderQuerySet object at 0x7fceb098d350>>

    In [25]: print(GASSupplierOrder.objects.closed)
    <bound method OrderManagerFromOrderQuerySet.closed of <django.utils.deprecation.OrderManagerFromOrderQuerySet object at 0x7fceb098d350>>

    In [26]: print(GASSupplierOrder.objects.archived)
    <bound method OrderManagerFromOrderQuerySet.archived of <django.utils.deprecation.OrderManagerFromOrderQuerySet object at 0x7fceb098d350>>

**Comment by feroda** [comment]
> Ho rimosso i commenti precedenti perche' portano fuori strada. Investigando piu' a fondo ho visto che gli ordini che vengono mostrati di fatto sono aperti (il loro metodo `is_open` ritorna `True`). 

non so se rimuovere i commenti è la mossa adatta, forse avrei preferito leggere 2 o 3 commenti in più e vedere il processo che ha portato alle deduzioni che poi si sono rivelate corrette.

In ogni caso va bene così. Questa issue si può chiudere. Bisogna solo tenere presente che la data di chiusura è una informazione collegata all'ordine, ma è necessario chiamare il metodo `close()` per chiuderlo effettivamente. Attualmente questo viene fatto da un processo in `cron` sul server invocando un comando Django custom che si chiama `order_fix_state`.

Sul fatto se questa gestione è bene che sia fatta in 2 fasi, o è bene legare il timestamp di chiusura dell'ordine alla chiusura effettiva, farei un breve passaggio con Dominique anche se credo che si possa tranquillamente legare lo stato alla data o meglio, derivarlo.

@michelesr letto e compreso ciò, apri una issue su questa ultima considerazione e puoi chiudere questa issue per l'alpha.
