### ISSUE TITLE
[Frontend]: File statici icone  css non caricati

### ISSUE THREAD

**Issue by michelesr** [befair/gasistafelice#163]
Alcuni file statici non vengono caricati.

![2015-09-21-195044_1366x768_scrot](https://cloud.githubusercontent.com/assets/2516077/10000125/8c4eb63c-609a-11e5-987b-81075b34215d.png)

**Comment by kobe25** [comment]
Probabilmente e' in qualche modo dovuto al mio recente commit 8c61fabe che sposta Bootstrap come dipendenza esterna, cancellando i file hardcodati.

Avevo fatto quest'operazione perche' non risultava che Bootstrap (almeno come css, e quindi anche fonts) venisse affatto caricato dall'`index.html` e quindi non ci sarebbero dovuti essere problemi.  Tra l'altro ho fatto una cosa simile con Font Awesome in un altro commit, che invece sembra funzionare.

Eppure Bootstrap c'e'!

**Comment by kobe25** [comment]
Andando un po' piu' a fondo, ho scoperto che il css di Bootstrap e' in qualche modo incluso in `ui/css/style.css`.  Quindi mentre il css funziona, i fonts non vengono trovati perche' non vengono cercati nella directory di Bootstrap con tutte le altre dipendenze esterne, ma nella cartella stessa dell'applicazione!

**Comment by kobe25** [comment]
A questo punto la domanda sorge spontanea.

@feroda perche' Bootstrap non viene incluso nell'`index.html` come dipendenza esterna (come tutti gli altri) ma invece e' stato hardcodato in `ui/css/style.css`?

**Comment by feroda** [comment]
@kobe25 forse perché è stato seguito un workflow tipo questo: http://www.helloerik.com/bootstrap-3-less-workflow-tutorial :)

...indago meglio che sarebbe bene chiudere questa issue...

**Comment by feroda** [comment]
direi di fare un link simbolico da ui/fonts a bower_components/bootstrap/dist/fonts/ e in questo modo di tappare il buco.

Aprire un'altra issue: "review less stylesheets" con priorità minima. Non ci serve per la consegna

**Comment by kobe25** [comment]
Ok, ma dovremo scrivere almeno un test per questo.

@michelesr qual e' la via per testare la presenza di file statici?
