### ISSUE TITLE
Branch di riferimento per la produzione

### ISSUE THREAD

**Issue by kobe25** [befair/gasistafelice#83]
Come da oggetto, attualmente manca un branch `stable`.

**Comment by OrlyMar** [comment]
Allo stesso modo non sarebbe da definirne anche uno Test

**Comment by kobe25** [comment]
@warp10

**Comment by feroda** [comment]
tagghiamo il branch stable pls a fronte di quanto fatto insieme a Medicina

**Comment by kobe25** [comment]
ping @warp10

**Comment by warp10** [comment]
Aggiunto i branch:
* stable (branchato da master)
* stable-dj17 (branchato da master-dj17)
