### ISSUE TITLE
Il login sull'interfaccia angular non si riflette sull'interfaccia legacy

### ISSUE THREAD

**Issue by michelesr** [befair/gasistafelice#88]
Questo fa si che alcune risorse, come ad esempio `/gasistafelice/rest/gasmember/1/order/edit_multiple` utilizzata nell'aggiunta al paniere tramite interfaccia angular non va a buon fine.

Affinche' la richiesta vada a buon fine l'utente si deve loggare nel frontend legacy e ripetere in seguito la richiesta dalla nuova interfaccia.

**Comment by kobe25** [comment]
Potrebbe essere piu' rapido aggiungere una nuova API `/api/v1/gasmember`?

**Comment by feroda** [comment]
Come programma di migrazione (dobbiamo fare una roadmap) dovremmo mettere una API POST per la modifica del listino.

Ma oggi è fondamentale per noi accedere in POST all'interfaccia legacy ed è fondamentale anche per i test come diceva @michelesr . Quindi ho studiato in treno la situazione con @matteo88 .

La conclusione è di implementare:
* backend di autenticazione Django (classico) basato su JWT
* fare in modo che il client legacy mandi l'header di autenticazione JWT
in questo modo droppiamo l'autenticazione basata su sessionid

Che ne pensate? Analizzando la situazione ho capito che non è possbile/oppurtuno né autenticare l'utente su entrambi i backend al momento del login, né fare in modo che i decoratori/check di autenticazione/autorizzazione in Django vadano a pescare dallo stesso backend (JWT). O meglio, il modo più corretto di far avvenire automaticamente questa cosa è di sovrascrivere il backend di autenticazione base di Django.

**Comment by kobe25** [comment]
Questo si basa sul *Django REST Framework JWT* che gia' usiamo per le nuove API, penso possa fare al caso nostro:

https://github.com/jpadilla/django-jwt-auth

**Comment by feroda** [comment]
Interessante, io stavo invece pensando che, premesso sempre che il dominio è unico, potremmo raggiungere il risultato realizzando una classe di autenticazione per Django REST Framework che autentichi con entrambi i backend (basta verificare che in risposta vegna settato anche il cookie di una sessionid valida). Questo ha il beneficio di non cambiare il client legacy e inoltre... 

... di prima mattina... voi sapreste come fare ad iniettare un header ad un link aperto in una scheda da un browsr? L'unica mi sa è fargli aprire il link di una pagina non autenticata e poi fare una richiesta ajax con l'header aggiunto ... o sono ancora addormentato io?

**Comment by feroda** [comment]
Ragazzi ho proferito chiudere il bug portando sia il REST Framework sia Django Legacy sul vecchio SessionAuthentication. È venuto abbastanza bene. Come avete visto dal potente github ho aperto il #92.

@michelesr vai! ora sei libero di testautomatizzare!
