### ISSUE TITLE
[NG] La modifica delle quantita' nel paniere non si riflettono sui parametri della POST

### ISSUE THREAD

**Issue by michelesr** [befair/gasistafelice#99]
Questo dipende dal fatto che mentre nella pagina degli ordini viene usato `ng-repeat` per iterare i vari prodotti presenti nel root scope, nel `ng-repeat` utilizzato in `basket.html` si itera sulla variabile `basket.closed_ordered_products` ... ora, siccome il metodo che viene lanciato tramite `ng-blur` passa direttamente il riferimento al prodotto, nel primo caso il prodotto viene aggiornato perche' il reference punta al prodotto che sta nella lista collegata al root scope, nel secondo caso viene aggiornato il prodotto che sta in una lista indipendente. Di conseguenza, al lancio di `updateBasket()` dal controller del basket i prodotti non vengono aggiornati, perche' la POST contiene gli stessi parametri di partenza.

**Comment by michelesr** [comment]
Soluzione proposta, togliere la variabile `basket.closed_ordered_products` e utilizzare un filtro per determinare quali prodotti mostrare nella view.

**Comment by michelesr** [comment]
Un'altra possibile soluzione e' mappare in qualche modo il reference del prodotto ordinato al prodotto nel listino...

invece di lanciare `change(product)` o simili, si puo' lanciare un metodo che fa da tramite, sostituisce il ref e lancia il metodo originario.

**Comment by feroda** [comment]
I 2 bottoni, per quanto simili all'apparenza, fanno POST a 2 url diversi: 
* `/gasistafelice/rest/gasmember/:gasmember_id/order/edit_multiple`
* `/gasistafelice/rest/gasmember/:gasmember_id/backet/edit_multiple`

Per l'implementazione procederei come nella funzione `getTotal`, passando la lista di prodotti in input e sopratutto implementando un nuovo metodo che è `updateCart`. Ho rinominato anche il precedente metodo `updateBasket` in `addToCart`

**Comment by feroda** [comment]
Sorry il commento era per il #98 :)

La questione ng-blur la rivedo a parte
